# Generated by Django 3.1.4 on 2020-12-15 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blackbook', '0002_add_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('icon', models.CharField(default='fa-coins', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True, verbose_name='active?')),
                ('include_in_net_worth', models.BooleanField(default=True, help_text='Include this account when calculating total net worth?', verbose_name='include in net worth?')),
                ('iban', localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, null=True, use_nordea_extensions=False, verbose_name='IBAN')),
                ('currency', djmoney.models.fields.CurrencyField(choices=[('ALL', 'Albanian Lek'), ('EUR', 'Euro'), ('AMD', 'Armenian Dram'), ('AZN', 'Azerbaijani Manat'), ('BYN', 'Belarusian Ruble'), ('BAM', 'Bosnia-Herzegovina Convertible Mark'), ('BGN', 'Bulgarian Lev'), ('HRK', 'Croatian Kuna'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('GEL', 'Georgian Lari'), ('HUF', 'Hungarian Forint'), ('ISK', 'Icelandic Króna'), ('CHF', 'Swiss Franc'), ('MDL', 'Moldovan Leu'), ('MKD', 'Macedonian Denar'), ('NOK', 'Norwegian Krone'), ('PLN', 'Polish Zloty'), ('RON', 'Romanian Leu'), ('RUB', 'Russian Ruble'), ('RSD', 'Serbian Dinar'), ('SEK', 'Swedish Krona'), ('TRY', 'Turkish Lira'), ('UAH', 'Ukrainian Hryvnia'), ('GBP', 'British Pound')], default='EUR', max_length=3)),
                ('virtual_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter a number here to have BlackBook treat this as the new zero point for this account. Leave at 0.0 to disable.', max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='blackbook.accounttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('account_owner', 'Account owner'), ('account_viewer', 'Account viewer')],
            },
        ),
    ]
