# Generated by Django 3.1.4 on 2020-12-15 21:06

from django.db import migrations


def create_default_values(apps, schema_editor):
    AccountType = apps.get_model("blackbook", "AccountType")

    initial_data = [
        ("Asset account", "fa-landmark"),
        ("Cash account", "fa-money-bill"),
        ("Credit card account", "fa-credit-card"),
        ("Expense account", "fa-coins"),
        ("Loan", "fa-file-invoice-dollar"),
        ("Mortgage", "fa-home"),
        ("Revenue account", "fa-donate"),
        ("Savings account", "fa-piggy-bank"),
    ]

    for account_type in initial_data:
        at_object, created = AccountType.objects.get_or_create(name=account_type[0])

        at_object.icon = account_type[1]
        at_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blackbook", "0003_add_account_model"),
    ]

    operations = [migrations.RunPython(create_default_values)]
