# Generated by Django 3.1.4 on 2020-12-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0007_add_transaction_transactionjournalentry_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='transactionjournalentry',
            options={'get_latest_by': 'date', 'ordering': ['date', 'created'], 'verbose_name_plural': 'transaction journal entries'},
        ),
    ]
