# Generated by Django 3.1.4 on 2020-12-20 16:26

from django.db import migrations

from ..utilities import unique_slugify


def create_default_values(apps, schema_editor):
    AccountType = apps.get_model("blackbook", "AccountType")

    for account_type in AccountType.objects.all():
        unique_slugify(account_type, account_type.name)
        account_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blackbook", "0009_add_slug_field_to_account"),
    ]

    operations = [migrations.RunPython(create_default_values)]
