# Generated by Django 3.1.4 on 2020-12-22 22:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0010_save_account_types_to_generate_slug'),
    ]

    operations = [
        
    ]
