# Generated by Django 3.1.4 on 2020-12-22 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0011_updated_primary_key_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='transactionjournalentry',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transactionjournalentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
