# Generated by Django 3.1.4 on 2020-12-23 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0013_add_uuid_to_other_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionjournalentry',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='blackbook.budgetperiod'),
        ),
    ]
