# Generated by Django 3.1.4 on 2020-12-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0014_relinking_transactions_to_budgetperiods'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='include_on_dashboard',
            field=models.BooleanField(default=True, help_text='Include this account on the graph on the frontpage?', verbose_name='include in graph on dashboard?'),
        ),
    ]
