# Generated by Django 3.1.4 on 2020-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0015_add_toggle_for_frontpage_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='include_on_dashboard',
            field=models.BooleanField(default=True, help_text='Include this account on the graph on the frontpage?', verbose_name='include on dashboard?'),
        ),
    ]
