# Generated by Django 3.1.4 on 2020-12-28 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0016_add_toggle_for_frontpage_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionjournalentry',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_transactions', to='blackbook.account'),
        ),
        migrations.AddField(
            model_name='transactionjournalentry',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_transactions', to='blackbook.account'),
        ),
    ]
