# Generated by Django 3.1.4 on 2020-12-28 22:04

from django.db import migrations


def create_default_values(apps, schema_editor):
    TransactionJournalEntry = apps.get_model("blackbook", "TransactionJournalEntry")
    Transaction = apps.get_model("blackbook", "Transaction")

    for transaction in TransactionJournalEntry.objects.all():
        try:
            transaction.to_account = transaction.transactions.get(amount__gte=0.0).account

        except Transaction.DoesNotExist:
            pass

        try:
            transaction.from_account = transaction.transactions.get(amount__lte=0.0).account

        except Transaction.DoesNotExist:
            pass

        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blackbook", "0017_add_to_from_account_as_field"),
    ]

    operations = [migrations.RunPython(create_default_values)]
