# Generated by Django 3.1.4 on 2021-01-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0018_populate_to_from_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactionjournalentry',
            name='user',
        ),
    ]
