# Generated by Django 3.1.4 on 2021-01-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0021_update_account_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetperiod',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='transactionjournalentry',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='transactionjournalentry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transactionjournalentry',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='transactionjournalentry',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='transactionjournalentry',
            name='to_account',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='BudgetPeriod',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionJournalEntry',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
