# Generated by Django 3.1.4 on 2021-01-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0025_add_sub_account_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('assetaccount', 'asset account'), ('revenueaccount', 'revenue account'), ('expenseaccount', 'expense account'), ('liabilitiesaccount', 'liabilities'), ('cashaccount', 'cash account')], max_length=50),
        ),
    ]
