# Generated by Django 3.1.4 on 2021-01-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0027_userprofile_update_relationship_to_one_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('assetaccount', 'Asset Account'), ('revenueaccount', 'Revenue Account'), ('expenseaccount', 'Expense Account'), ('liabilitiesaccount', 'Liabilities'), ('cashaccount', 'Cash Account')], max_length=50),
        ),
    ]
