# Generated by Django 3.1.4 on 2021-01-23 21:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0028_updated_account_type_pretty_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('start', 'Opening balance'), ('reconciliation', 'Reconciliation'), ('transfer', 'Transfer'), ('withdrawal', 'Withdrawal')], default='withdrawal', max_length=50)),
                ('amount_source_currency_currency', djmoney.models.fields.CurrencyField(choices=[('AMD', 'Armenian Dram'), ('AZN', 'Azerbaijanian Manat'), ('BYN', 'Belarussian Ruble'), ('BGN', 'Bulgarian Lev'), ('BAM', 'Convertible Marks'), ('HRK', 'Croatian Kuna'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('MKD', 'Denar'), ('EUR', 'Euro'), ('HUF', 'Forint'), ('UAH', 'Hryvnia'), ('ISK', 'Iceland Krona'), ('GEL', 'Lari'), ('ALL', 'Lek'), ('MDL', 'Moldovan Leu'), ('RON', 'New Leu'), ('NOK', 'Norwegian Krone'), ('GBP', 'Pound Sterling'), ('RUB', 'Russian Ruble'), ('RSD', 'Serbian Dinar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('TRY', 'Turkish Lira'), ('PLN', 'Zloty')], default='EUR', editable=False, max_length=3)),
                ('amount_source_currency', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('amount_destination_currency_currency', djmoney.models.fields.CurrencyField(choices=[('AMD', 'Armenian Dram'), ('AZN', 'Azerbaijanian Manat'), ('BYN', 'Belarussian Ruble'), ('BGN', 'Bulgarian Lev'), ('BAM', 'Convertible Marks'), ('HRK', 'Croatian Kuna'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('MKD', 'Denar'), ('EUR', 'Euro'), ('HUF', 'Forint'), ('UAH', 'Hryvnia'), ('ISK', 'Iceland Krona'), ('GEL', 'Lari'), ('ALL', 'Lek'), ('MDL', 'Moldovan Leu'), ('RON', 'New Leu'), ('NOK', 'Norwegian Krone'), ('GBP', 'Pound Sterling'), ('RUB', 'Russian Ruble'), ('RSD', 'Serbian Dinar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('TRY', 'Turkish Lira'), ('PLN', 'Zloty')], default='EUR', editable=False, max_length=3)),
                ('amount_destination_currency', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_account', to='blackbook.account')),
                ('linked_transactions', models.ManyToManyField(blank=True, null=True, related_name='_transaction_linked_transactions_+', to='blackbook.Transaction')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_account', to='blackbook.account')),
            ],
            options={
                'ordering': ['date', 'created'],
                'get_latest_by': 'date',
            },
        ),
    ]
