# Generated by Django 3.1.4 on 2021-01-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0030_update_transaction_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='linked_transactions',
            field=models.ManyToManyField(blank=True, related_name='_transaction_linked_transactions_+', to='blackbook.Transaction'),
        ),
    ]
