# Generated by Django 3.1.4 on 2021-01-23 21:55

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0031_allow_linked_transactions_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_destination_currency',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='destination amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_source_currency',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='source amount'),
        ),
    ]
