# Generated by Django 3.1.4 on 2021-01-30 15:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0032_updated_description_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'created'],
                'get_latest_by': 'date',
            },
        ),
    ]
