# Generated by Django 3.1.4 on 2021-01-30 17:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0033_add_transactionjournal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_destination_currency_currency',
            new_name='amount_currency',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_source_currency_currency',
            new_name='foreign_amount_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_destination_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_source_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='linked_transactions',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='short_description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='foreign_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='foreign amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blackbook.transactionjournal'),
            preserve_default=False,
        ),
    ]
