# Generated by Django 3.1.4 on 2021-01-31 08:42

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0034_updated_transaction_with_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='foreign_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=15, null=True, verbose_name='foreign amount'),
        ),
    ]
