# Generated by Django 3.2rc1 on 2021-03-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blackbook", "0035_allow_foreign_amount_null"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="AssetAccount",
        ),
        migrations.DeleteModel(
            name="CashAccount",
        ),
        migrations.DeleteModel(
            name="ExpenseAccount",
        ),
        migrations.DeleteModel(
            name="LiabilitiesAccount",
        ),
        migrations.DeleteModel(
            name="RevenueAccount",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.DeleteModel(
            name="TransactionJournal",
        ),
    ]
