# Generated by Django 3.2rc1 on 2021-03-27 11:11

from django.db import migrations, models
import djmoney.models.fields
import localflavor.generic.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0036_auto_20210327_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active?')),
                ('net_worth', models.BooleanField(default=True, help_text='Include this account when calculating total net worth?', verbose_name='include in net worth?')),
                ('dashboard', models.BooleanField(default=True, help_text='Show this transaction on the dashboard?', verbose_name='show on dashboard?')),
                ('currency', djmoney.models.fields.CurrencyField(choices=[('ALL', 'Albanian Lek'), ('EUR', 'Euro'), ('AMD', 'Armenian Dram'), ('AZN', 'Azerbaijani Manat'), ('BYN', 'Belarusian Ruble'), ('BAM', 'Bosnia-Herzegovina Convertible Mark'), ('BGN', 'Bulgarian Lev'), ('HRK', 'Croatian Kuna'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('GEL', 'Georgian Lari'), ('HUF', 'Hungarian Forint'), ('ISK', 'Icelandic Króna'), ('CHF', 'Swiss Franc'), ('MDL', 'Moldovan Leu'), ('MKD', 'Macedonian Denar'), ('NOK', 'Norwegian Krone'), ('PLN', 'Polish Zloty'), ('RON', 'Romanian Leu'), ('RUB', 'Russian Ruble'), ('RSD', 'Serbian Dinar'), ('SEK', 'Swedish Krona'), ('TRY', 'Turkish Lira'), ('UAH', 'Ukrainian Hryvnia'), ('GBP', 'British Pound')], default='EUR', max_length=3)),
                ('virtual_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter a number here to have BlackBook treat this as the new zero point for this account. Default should always be 0.0', max_digits=15)),
                ('type', models.CharField(choices=[('assetaccount', 'Asset Account'), ('revenueaccount', 'Revenue Account'), ('expenseaccount', 'Expense Account'), ('liabilitiesaccount', 'Liabilities'), ('cashaccount', 'Cash Account')], max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('iban', localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, null=True, use_nordea_extensions=False, verbose_name='IBAN')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
