# Generated by Django 3.2rc1 on 2021-03-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0037_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
