# Generated by Django 3.2rc1 on 2021-04-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0039_transaction_transactionjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_account_transactions', to='blackbook.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_account_transactions', to='blackbook.account'),
        ),
    ]
