# Generated by Django 3.2rc1 on 2021-04-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0040_auto_20210425_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='negative',
            field=models.BooleanField(default=False),
        ),
    ]
