# Generated by Django 3.2rc1 on 2021-04-27 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0041_transaction_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blackbook.transactionjournal'),
        ),
    ]
