# Generated by Django 3.2rc1 on 2021-04-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0042_alter_transaction_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='destination_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='blackbook.account'),
        ),
        migrations.AddField(
            model_name='transactionjournal',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('start', 'Opening balance'), ('reconciliation', 'Reconciliation'), ('transfer', 'Transfer'), ('withdrawal', 'Withdrawal')], default='withdrawal', max_length=50),
        ),
    ]
