# Generated by Django 3.2rc1 on 2021-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0043_auto_20210428_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_accounts',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ource_accounts',
            field=models.JSONField(null=True),
        ),
    ]
