# Generated by Django 3.2rc1 on 2021-04-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0044_auto_20210429_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='ource_accounts',
            new_name='source_accounts',
        ),
    ]
