# Generated by Django 3.2rc1 on 2021-04-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0045_rename_ource_accounts_transaction_source_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionjournal',
            name='budget',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='transactionjournal',
            name='category',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
