# Generated by Django 3.2rc1 on 2021-05-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0047_auto_20210503_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionjournal',
            name='destination_accounts',
            field=models.JSONField(null=True),
        ),
    ]
