# Generated by Django 3.2rc1 on 2021-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0048_transactionjournal_destination_accounts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('type', 'name'), name='unique_account_name'),
        ),
    ]
