# Generated by Django 3.2rc1 on 2021-05-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0051_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionjournal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.category'),
        ),
    ]
