# Generated by Django 3.2rc1 on 2021-05-05 19:46

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0052_alter_transactionjournal_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True, verbose_name='active?')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('AMD', 'Armenian Dram'), ('AZN', 'Azerbaijanian Manat'), ('BYN', 'Belarussian Ruble'), ('BGN', 'Bulgarian Lev'), ('BAM', 'Convertible Marks'), ('HRK', 'Croatian Kuna'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('MKD', 'Denar'), ('EUR', 'Euro'), ('HUF', 'Forint'), ('UAH', 'Hryvnia'), ('ISK', 'Iceland Krona'), ('GEL', 'Lari'), ('ALL', 'Lek'), ('MDL', 'Moldovan Leu'), ('RON', 'New Leu'), ('NOK', 'Norwegian Krone'), ('GBP', 'Pound Sterling'), ('RUB', 'Russian Ruble'), ('RSD', 'Serbian Dinar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('TRY', 'Turkish Lira'), ('PLN', 'Zloty')], default='EUR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('auto_budget', models.CharField(choices=[('no', 'No auto-budget'), ('add', 'Add an amount each period'), ('fixed', 'Set a fixed amount each period')], default='no', max_length=30, verbose_name='auto-budget')),
                ('auto_budget_period', models.CharField(blank=True, choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('quarter', 'Quarterly'), ('half_year', 'Every 6 months'), ('year', 'Yearly')], default='week', max_length=30, null=True, verbose_name='auto-budget period')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
