# Generated by Django 3.2rc1 on 2021-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0053_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_period',
            field=models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('quarter', 'Quarterly'), ('half_year', 'Every 6 months'), ('year', 'Yearly')], default='month', max_length=30),
        ),
    ]
