# Generated by Django 3.2rc1 on 2021-05-05 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0055_budgetperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionjournal',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.budgetperiod'),
        ),
    ]
