# Generated by Django 3.2rc1 on 2021-05-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0056_alter_transactionjournal_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionjournal',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='blackbook.budgetperiod'),
        ),
        migrations.AlterField(
            model_name='transactionjournal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='blackbook.category'),
        ),
    ]
