# Generated by Django 3.2.2 on 2021-05-07 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0058_bonus_paycheck_paycheckitem_paycheckitemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
