# Generated by Django 3.2.2 on 2021-05-18 21:10

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0059_paycheck_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paycheck',
            old_name='amount',
            new_name='net_amount',
        ),
        migrations.RenameField(
            model_name='paycheck',
            old_name='amount_currency',
            new_name='net_amount_currency',
        ),
        migrations.AddField(
            model_name='paycheck',
            name='gross_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='gross_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AMD', 'Armenian Dram'), ('AZN', 'Azerbaijanian Manat'), ('BYN', 'Belarussian Ruble'), ('BGN', 'Bulgarian Lev'), ('BAM', 'Convertible Marks'), ('HRK', 'Croatian Kuna'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('MKD', 'Denar'), ('EUR', 'Euro'), ('HUF', 'Forint'), ('UAH', 'Hryvnia'), ('ISK', 'Iceland Krona'), ('GEL', 'Lari'), ('ALL', 'Lek'), ('MDL', 'Moldovan Leu'), ('RON', 'New Leu'), ('NOK', 'Norwegian Krone'), ('GBP', 'Pound Sterling'), ('RUB', 'Russian Ruble'), ('RSD', 'Serbian Dinar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('TRY', 'Turkish Lira'), ('PLN', 'Zloty')], default='EUR', editable=False, max_length=3),
        ),
    ]
