# Generated by Django 3.2.2 on 2021-05-18 21:11

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0060_auto_20210518_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='gross_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='gross amount'),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='net_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='net amount'),
        ),
    ]
