# Generated by Django 3.2.2 on 2021-05-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0061_auto_20210518_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
