# Generated by Django 3.2.2 on 2021-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0062_paycheck_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('assetaccount', 'Asset Account'), ('incomeaccount', 'Income Account'), ('expenseaccount', 'Expense Account'), ('liabilitiesaccount', 'Liabilities'), ('cashaccount', 'Cash Account')], max_length=50),
        ),
    ]
