# Generated by Django 4.0b1 on 2021-11-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0065_remove_account_unique_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='currency',
            new_name='currencies',
        ),
    ]
