# Generated by Django 4.0b1 on 2021-11-07 12:17

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0066_rename_currency_account_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blackbook.account'),
        ),
    ]
