# Generated by Django 4.0b1 on 2021-11-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0067_alter_account_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackbook.account')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.currency')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='foreign_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='foreign_amount_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='uuid',
        ),
        migrations.DeleteModel(
            name='TransactionJournal',
        ),
        migrations.AddField(
            model_name='transactionleg',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackbook.transaction'),
        ),
    ]
