# Generated by Django 4.0b1 on 2021-11-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0069_transaction_category_transaction_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'date', 'ordering': ['date', 'created']},
        ),
    ]
