# Generated by Django 4.0b1 on 2021-11-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0070_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionleg',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_legs', to='blackbook.transaction'),
        ),
    ]
