# Generated by Django 4.0b1 on 2021-11-11 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0071_alter_transactionleg_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('assets', 'Asset Account'), ('income', 'Income Account'), ('expenses', 'Expense Account'), ('liabilities', 'Liabilities'), ('cash', 'Cash Account')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionleg',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.currency'),
        ),
    ]
